name: 'GitHub Actions Mirror'

on:
  workflow_dispatch:
  schedule:
    - cron: '13 13 * * *'

jobs:

  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.1.1
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@gitlab.com:rwkgyg/x-ui-yg.git
          ssh_private_key:
            ${{ secrets.private_key }}
